# Generated by Django 5.1.1 on 2024-10-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudyRoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='name',
        ),
    ]
