# Generated by Django 5.1.1 on 2024-10-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyRoom', '0003_tag_room_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ManyToManyField(related_name='rooms', to='StudyRoom.topic'),
        ),
    ]
