# Generated by Django 5.1.1 on 2024-10-02 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyRoom', '0004_remove_room_tag_remove_room_topic_delete_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.AddField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='StudyRoom.topic'),
            preserve_default=False,
        ),
    ]
